/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // tutorialSidebar2: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
};

module.exports = {
  mySidebar: [
    {
      "Getting Started": [
        "intro",
        "app/start-server",
        {
          type: 'category',
          label: 'OneApp',
          items: [
            {
              type: "link",
              label: "Custom Application",
              href: "https://docs.rikdata.com/docs/customization/custom-application",
            },
            {
              type: "link",
              label: "Client Installation",
              href: "https://docs.rikdata.com/docs/quickstart",
            },
          ],
        },
      ],
    },
    {
      "Inventory": ["inv/item-master", "sd/inquiry"] 
    },
    {
      Sales: [
        "sd/inquiry",
        "sd/quote",
        "sd/sales-order",
        "sd/sales-agreement",
        "sd/delivery",
        "sd/configuration",
      ],
    },
    {
      Purchasing: [
        "purchasing/request-for-quotation",
        "purchasing/quotation",
        "purchasing/requisition",
        "purchasing/purchase-order",
        "purchasing/purchase-agreement",
        "purchasing/configuration",
      ],
    },
    {
      Manufacturing: [
        "manufacturing/routing",
        "manufacturing/bill-of-materials",
        "manufacturing/work-definition",
        "manufacturing/work-order",
        "manufacturing/wip-transaction",
      ],
    },
    {
      "Accounts Receivable": ["ar/customer","ar/transaction", "ar/payment", "ar/agreement", "ar/configuration"],
    },
    {
      "Accounts Payable": ["ap/supplier","ap/transaction","ap/agreement","ap/payment"],
    },
    {
      "About": ["privacy", "download"] 
    },
    {
      type: "link",
      label: "OneApp",
      href: "http://docs.rikdata.com",
    },
  ],
};

//module.exports = sidebars;
