/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // tutorialSidebar2: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
};

module.exports = {
  mySidebar: [
    {
      "Getting Started": [
        "intro",
        "app/start-server",
        {
          type: "category",
          label: "OneApp Client",
          items: [
            {
              type: "link",
              label: "Custom Application",
              href: "https://docs.rikdata.com/docs/customization/custom-application",
            },
            {
              type: "link",
              label: "Client Installation",
              href: "https://docs.rikdata.com/docs/quickstart",
            },
          ],
        },
      ],
    },
    {
      "General Ledger": [
        "gl/coa",
        "gl/calendar",
        "gl/currency",
        "gl/ledger",
        "gl/accounting",
        "gl/journal",
        "gl/payment_term",
      ],
    },
    {
      "Common Entities": [
        "mdm/organization",
        "sys/approval",
        "mdm/price-list",
        "mdm/bank",
        "mdm/tax-code",
      ],
    },
    {
      Inventory: [
        "inv/master-data",
        "inv/organization-data",
        "inv/transaction",
        "inv/control",
        "inv/onhand",
        "inv/config",
      ],
    },
    {
      Sales: [
        "sd/inquiry",
        "sd/quote",
        "sd/sales-order",
        "sd/sales-agreement",
        "sd/delivery",
        "sd/configuration",
      ],
    },
    {
      Purchasing: [
        "purchasing/request-for-quotation",
        "purchasing/quotation",
        "purchasing/requisition",
        "purchasing/purchase-order",
        "purchasing/purchase-agreement",
        "purchasing/configuration",
      ],
    },
    {
      Manufacturing: [
        "manufacturing/routing",
        "manufacturing/bill-of-materials",
        "manufacturing/work-definition",
        "manufacturing/work-order",
        "manufacturing/wip-transaction",
      ],
    },
    {
      Planning: ["fp/forecast", "fp/mds", "fp/mrp", "fp/planned_order"],
    },
    {
      Costing: ["cst/item-cost", "cst/frozen-cost", "cst/cost-config"],
    },
    {
      "Accounts Receivable": [
        "ar/customer",
        "ar/transaction",
        "ar/payment",
        "ar/agreement",
        "ar/configuration",
      ],
    },
    {
      "Accounts Payable": [
        "ap/supplier",
        "ap/transaction",
        "ap/agreement",
        "ap/payment",
      ],
    },
    {
      "Asset Accounting": [
        "fa/asset",
        "fa/depreciation",
        "fa/transaction",
        "fa/configuration",
      ],
    },
    {
      "Human Capital": [
        "hr/master-data",
        "hr/employee",
        "hr/leave",
        "hr/compensation",
        "hr/payroll",
        "hr/expense-claim",
        "hr/timesheet",

      ],
    },
    {
      About: ["privacy", "download"],
    },
    {
      type: "link",
      label: "OneApp",
      href: "http://docs.rikdata.com",
    },
  ],
};

//module.exports = sidebars;
